name: Collect Congress Data (118–119)

on:
  schedule:
    # Nightly at 09:30 UTC = 02:30 PT
    - cron: "30 9 * * *"
    # Weekly full refresh, Sundays 03:00 PT
    - cron: "00 10 * * 0"
  workflow_dispatch:

concurrency:
  group: collect-congress-data
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y wget python3-dev libxml2-dev libxslt1-dev libz-dev python3-venv jq zip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install congress tool from GitHub (usc-run)
        run: |
          python -m venv env
          . env/bin/activate
          pip install --upgrade pip
          pip install "git+https://github.com/unitedstates/congress.git"

      # --- Votes (existing behaviour) ---
      - name: Run votes scraper (sessions 118–119)
        env:
          SESSIONS: "118.2023,118.2024,119.2025"
        run: |
          . env/bin/activate
          if [ "${{ github.event.schedule }}" = "30 9 * * *" ]; then
            usc-run votes --sessions="${SESSIONS}" --fast --log=info
          else
            usc-run votes --sessions="${SESSIONS}" --log=info
          fi

      - name: List scraped vote files (debug)
        run: |
          echo "Listing vote JSON files…"
          find data -type f -path "*/votes/*/*/data.json" | sort | sed 's/^/  /' || true

      - name: Validate vote files exist
        run: |
          set -e
          COUNT=$(find data -type f -path "*/votes/*/*/data.json" | wc -l | tr -d ' ')
          echo "Found $COUNT vote JSON files"
          if [ "$COUNT" -eq 0 ]; then
            echo "::error::No vote JSON files were generated. Check sessions or network."
            exit 1
          fi

      # --- Bills: fetch govinfo bulk and process bills + bill text ---
      - name: Fetch GovInfo BILLSTATUS (118–119)
        run: |
          . env/bin/activate
          usc-run govinfo --bulkdata=BILLSTATUS --congress=118,119 --log=info

      - name: Process Bills (118–119)
        run: |
          . env/bin/activate
          usc-run bills --congress=118,119 --log=info

      - name: Fetch Bill Text (118–119)
        run: |
          . env/bin/activate
          usc-run billtext --congress=118,119 --log=info

      - name: List scraped bill files (debug)
        run: |
          echo "Listing bill metadata files…"
          find data -type f -path "*/bills/*/data.json" | sort | sed 's/^/  /' || true
          echo "Listing bill text files…"
          find data -type f -path "*/bills/*/text-versions/*/data.json" | sort | sed 's/^/  /' || true

      # --- Build manifests (votes, bills, billtext) ---
      - name: Build manifests (votes, bills, billtext)
        run: |
          set -e

          # votes manifest
          echo '{"files":[' > manifest.json
          first=true
          find data -type f -path "*/votes/*/*/data.json" | sort | while read -r f; do
            if [ "$first" = true ]; then first=false; else echo "," >> manifest.json; fi
            printf '"%s"' "$f" >> manifest.json
          done
          echo "]}" >> manifest.json
          echo "Votes manifest built: $(jq '.files | length' manifest.json) files"

          # bills manifest
          echo '{"files":[' > bills-manifest.json
          first=true
          find data -type f -path "*/bills/*/data.json" | sort | while read -r f; do
            if [ "$first" = true ]; then first=false; else echo "," >> bills-manifest.json; fi
            printf '"%s"' "$f" >> bills-manifest.json
          done
          echo "]}" >> bills-manifest.json
          echo "Bills manifest built: $(jq '.files | length' bills-manifest.json) files"

          # bill text manifest
          echo '{"files":[' > billtext-manifest.json
          first=true
          find data -type f -path "*/bills/*/text-versions/*/data.json" | sort | while read -r f; do
            if [ "$first" = true ]; then first=false; else echo "," >> billtext-manifest.json; fi
            printf '"%s"' "$f" >> billtext-manifest.json
          done
          echo "]}" >> billtext-manifest.json
          echo "BillText manifest built: $(jq '.files | length' billtext-manifest.json) files"

      # --- Final validation (optional) ---
      - name: Quick manifest counts for debug
        run: |
          echo "Votes files: $(jq '.files | length' manifest.json || echo 0)"
          echo "Bills files: $(jq '.files | length' bills-manifest.json || echo 0)"
          echo "BillText files: $(jq '.files | length' billtext-manifest.json || echo 0)"

      # --- Archive everything for n8n to fetch ---
      - name: Archive data
        run: |
          mkdir -p out
          # include the data tree + manifests
          zip -r out/congress-data.zip data manifest.json bills-manifest.json billtext-manifest.json

      - name: Upload artifact (congress data)
        uses: actions/upload-artifact@v4
        with:
          name: congress-data
          path: out/congress-data.zip
          if-no-files-found: error
          retention-days: 7
