name: Collect Bulk Bill Text (119)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 10 * * *" # daily at 10:00 UTC

concurrency:
  group: collect-bulk-billtext
  cancel-in-progress: true

permissions:
  contents: read

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET || 'congress-legislative-data' }}
  GCS_PREFIX: ${{ secrets.GCS_PREFIX || 'congress-billtext-data' }}
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  fetch_bulk_billtext:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget rsync unzip jq python3-venv

      # Step 1: Sync from GovInfo bulkdata (direct HTTP scrape)
      - name: Download bulk bill text from GovInfo
        run: |
          set -euo pipefail
          mkdir -p data/119
          echo "Downloading bill text from govinfo.gov bulkdata..."
          wget -r -np -nH -R "index.html*" -c \
            https://www.govinfo.gov/bulkdata/BILLS/119/ \
            -P data/119

          echo "Sample files downloaded:"
          find data/119 -type f | head -n 20

      # Step 2: Normalize structure if needed
      - name: Normalize bulkdata directory
        run: |
          set -euo pipefail
          echo "Normalizing govinfo bulkdata structure..."
          # Convert uppercase -> lowercase dirs (hr, s, sjres, etc.)
          find data/119 -depth -name "*" -execdir bash -c 'mv "$1" "$(echo $1 | tr A-Z a-z)"' bash {} \; || true

      # Step 3: Build manifest.json
      - name: Build Bill Text Manifest
        run: |
          set -euo pipefail
          echo "Building billtext-manifest.json..."
          COUNT=$(find data/119 -type f -name "*.xml" | wc -l)
          jq -n --arg count "$COUNT" --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --argjson files "$(find data/119 -type f -name '*.xml' | jq -R -s -c 'split("\n")[:-1]')" \
            '{created_at:$ts, file_count:$count|tonumber, files:$files}' > billtext-manifest.json

          echo "Manifest created with $COUNT files"
          head -n 40 billtext-manifest.json

      # Step 4: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          version: '>= 472.0.0'

      # Step 5: Upload to GCS
      - name: Upload bill text to GCS
        run: |
          set -euo pipefail
          PREFIX="${GCS_PREFIX%/}"
          TARGET_PREFIX="${PREFIX:+${PREFIX}/}bulkdata/119"
          echo "Syncing local -> GCS at gs://${GCS_BUCKET}/${TARGET_PREFIX}"
          gsutil -m rsync -r "data/119" "gs://${GCS_BUCKET}/${TARGET_PREFIX}"

      - name: Upload manifest to GCS
        run: |
          set -euo pipefail
          PREFIX="${GCS_PREFIX%/}"
          GS_PREFIX="${PREFIX:+${PREFIX}/}manifests"
          echo "Uploading manifest file to gs://${GCS_BUCKET}/${GS_PREFIX}/"
          gsutil -m cp -n billtext-manifest.json "gs://${GCS_BUCKET}/${GS_PREFIX}/" || true

      - name: Summary
        run: |
          echo "Completed bulk billtext sync"
          echo "Bucket: ${GCS_BUCKET}"
          echo "Prefix: ${GCS_PREFIX}/bulkdata/119"
          echo "Manifest: billtext-manifest.json"
          jq '.file_count' billtext-manifest.json
