name: Collect Congress Bill Text (119)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 9 * * *" # nightly (09:30 UTC)

concurrency:
  group: collect-congress-billtext-xml
  cancel-in-progress: true

permissions:
  contents: read

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET || 'congress-legislative-data' }}
  GCS_PREFIX: ${{ secrets.GCS_PREFIX || 'congress-billtext-xml' }}
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  BILL_TYPES: "hr s hjres sjres hconres sconres hres sres"

jobs:
  download_billtext:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update -y && sudo apt-get install -y jq curl python3 python3-pip

      - name: Fetch bulkdata + normalize
        run: |
          set -euo pipefail
          mkdir -p data/119/bills
          BASE_URL="https://www.govinfo.gov/bulkdata/json/BILLS/119/1"

          for BT in $BILL_TYPES; do
            echo "Fetching $BT..."
            curl -s "${BASE_URL}/${BT}" -H "Accept: application/json" | \
              jq -r '.files[].url' | while read -r URL; do
                [ -z "$URL" ] && continue
                FNAME=$(basename "$URL")
                BILL_DIR="data/119/bills/${BT}/${FNAME%.*}"
                mkdir -p "$BILL_DIR"
                if [ ! -f "$BILL_DIR/$FNAME" ]; then
                  curl -s -L "$URL" -o "$BILL_DIR/$FNAME"
                fi
              done
          done

          python3 <<'EOF'
          import pathlib, json, re
          from datetime import datetime
          base = pathlib.Path("data/119/bills")
          count = 0

          for xml in base.rglob("*.xml"):
              fname = xml.name
              m = re.match(r"BILLS-(\d+)([a-z]+)(\d+)([a-z]+)\.xml", fname, re.I)
              if not m: continue
              congress, bt, num, version = m.groups()
              bill_id = f"{bt}{int(num)}-{congress}".lower()
              pkg = fname.replace(".xml","")
              urls = {ext: f"https://www.govinfo.gov/content/pkg/{pkg}/{ext}/{pkg}.{ext}"
                      for ext in ("html","pdf","xml")}
              meta = {
                "bill_id": bill_id,
                "version_code": version.lower(),
                "issued_on": datetime.utcfromtimestamp(xml.stat().st_mtime).strftime("%Y-%m-%d"),
                "urls": urls,
              }
              (xml.parent/"data.json").write_text(json.dumps(meta, indent=2))
              count += 1

          with open("billtext-manifest.json","w") as f:
              json.dump({
                "file_count": count,
                "generated_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
              }, f, indent=2)
          EOF

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Upload to GCS
        run: |
          gsutil -m rsync -r data/119 "gs://${GCS_BUCKET}/${GCS_PREFIX}/data/119"
          gsutil -m cp -n billtext-manifest.json "gs://${GCS_BUCKET}/${GCS_PREFIX}/manifests/"

      - name: Summary
        run: cat billtext-manifest.json
