name: Bill Text Congress 119

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 9 * * *" # daily

concurrency:
  group: sync-billtext-xml
  cancel-in-progress: true

permissions:
  contents: read

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET || 'congress-legislative-data' }}
  GCS_PREFIX: ${{ secrets.GCS_PREFIX || 'congress-billtext-xml' }}
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  sync_billtext:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget jq

      - name: Download bill XML from GovInfo
        run: |
          set -euo pipefail
          mkdir -p data/119
          cd data/119
          BILL_TYPES=("hconres" "hjres" "hr" "hres" "s" "sconres" "sjres" "sres")
          for TYPE in "${BILL_TYPES[@]}"; do
            echo "Downloading $TYPE..."
            wget -r -np -nH -N --cut-dirs=3 \
              https://www.govinfo.gov/bulkdata/BILLS/119/1/$TYPE/ \
              -A "*.xml"
          done

      - name: Build manifest
        run: |
          cd data/119
          find . -type f -name "*.xml" | sort | jq -R . | jq -s '{file_count: length, files: .}' > billtext-manifest.json
          cat billtext-manifest.json

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Upload bill XML to GCS
        run: |
          gsutil -m rsync -r data/119 "gs://${GCS_BUCKET}/${GCS_PREFIX}/data/119"

      - name: Upload manifest
        run: |
          gsutil cp billtext-manifest.json "gs://${GCS_BUCKET}/${GCS_PREFIX}/manifests/"
      
      - name: Summary
        run: |
          echo "Completed bulk billtext sync"
          echo "Bucket: ${GCS_BUCKET}"
          echo "Prefix: ${GCS_PREFIX}/data/119"
          jq '.file_count' data/119/billtext-manifest.json
