name: Collect Congress Bill Text (119)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 9 * * *" # nightly (09:30 UTC)

concurrency:
  group: collect-congress-billtext
  cancel-in-progress: true

permissions:
  contents: read

env:
  CONGRESSES: ${{ secrets.CONGRESSES || '119' }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET || 'congress-legislative-data' }}
  GCS_PREFIX: ${{ secrets.GCS_PREFIX || 'congress-billtext-data' }}
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

jobs:
  # ----------------------
  # Matrix: Fetch raw bill data by type
  # ----------------------
  fetch_billtext:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bill_type: [hr, s, hjres, sjres, hconres, sconres, hres, sres]
      fail-fast: false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install System Libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-venv jq zip unzip rsync

      - name: Create venv & install Congress tool
        run: |
          python -m venv env
          . env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install "git+https://github.com/unitedstates/congress.git"
          python -m pip install -e .
          echo "PYTHON=./env/bin/python" >> $GITHUB_ENV
          echo "PYTHONUNBUFFERED=1" >> $GITHUB_ENV

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          version: '>= 472.0.0'

      - name: Restore previous data from GCS
        run: |
          set -euo pipefail
          mkdir -p data/119/bills/${{ matrix.bill_type }}
          PREFIX="${GCS_PREFIX%/}"
          TARGET_PREFIX="${PREFIX:+${PREFIX}/}data/119/bills/${{ matrix.bill_type }}"
          echo "Syncing GCS -> local data for Congress 119, type ${{ matrix.bill_type }}"
          gsutil -m rsync -r "gs://${GCS_BUCKET}/${TARGET_PREFIX}" "data/119/bills/${{ matrix.bill_type }}" || true

      - name: Fetch GOVInfo Bill Text by type (incremental)
        run: |
          set -euo pipefail
          . env/bin/activate
          IFS=',' read -ra CONS <<< "${CONGRESSES}"
          for C in "${CONS[@]}"; do
            echo "Fetching Congress $C, type ${{ matrix.bill_type }}"
            usc-run govinfo \
              --collections=BILLS \
              --congress="$C" \
              --bill-type=${{ matrix.bill_type }} \
              --store=mods,xml,text \
              --bulkdata="False" \
              || { echo "::error:: usc-run govinfo failed for Congress $C ${{ matrix.bill_type }}"; exit 1; }
          done

      - name: Upload updated data back to GCS
        run: |
          set -euo pipefail
          PREFIX="${GCS_PREFIX%/}"
          TARGET_PREFIX="${PREFIX:+${PREFIX}/}data/119/bills/${{ matrix.bill_type }}"
          echo "Syncing local -> GCS for ${{ matrix.bill_type }}"
          gsutil -m rsync -r "data/119/bills/${{ matrix.bill_type }}" "gs://${GCS_BUCKET}/${TARGET_PREFIX}"

  # ----------------------
  # Aggregation Job
  # ----------------------
  aggregate_billtext:
    runs-on: ubuntu-latest
    needs: fetch_billtext

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install System Libs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-venv jq zip unzip rsync

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          version: '>= 472.0.0'

      - name: Restore full data tree from GCS
        run: |
          set -euo pipefail
          mkdir -p data
          PREFIX="${GCS_PREFIX%/}"
          TARGET_PREFIX="${PREFIX:+${PREFIX}/}data/119"
          echo "Syncing GCS -> local full data for Congress 119..."
          gsutil -m rsync -r "gs://${GCS_BUCKET}/${TARGET_PREFIX}" "data/119"

      - name: Unzip billtext packages
        run: |
          set -euo pipefail
          echo "Unzipping any package.zip files under data/ ..."
          found=0
          find data -type f -name 'package.zip' -print0 | while IFS= read -r -d '' zipfile; do
            found=1
            dir="$(dirname "$zipfile")"
            echo "Extracting: $zipfile -> $dir"
            if unzip -o "$zipfile" -d "$dir"; then
              echo "OK: $zipfile extracted"
            else
              echo "::warning:: Failed to extract $zipfile — continuing to next file"
            fi
          done
          if [ "$found" -eq 0 ]; then
            echo "No package.zip files found (this can be okay if upstream writes files directly)."
          fi

      - name: Quick Debug
        run: |
          echo "Total data.json files under data/: $(find data -type f -name data.json | wc -l || true)"
          echo "Sample text-version data.json (data/*/bills/*/*/text-versions/*/data.json):"
          find data -type f -path "data/*/bills/*/*/text-versions/*/data.json" | sort | sed -n '1,100p' || true

      - name: Run usc-run billtext
        run: |
          python -m venv env
          . env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install "git+https://github.com/unitedstates/congress.git"
          python -m pip install -e .
          usc-run billtext

      - name: Build Latest Bill Text
        run: |
          . env/bin/activate
          $PYTHON -u scripts/latest-bill-text.py

      - name: Debug Bill Text
        run: |
          echo "latest_billtext exists?"; [ -d latest_billtext ] && echo "yes" || echo "no"
          echo "latest_billtext data.json count:"; find latest_billtext -type f -name data.json | wc -l || true
          echo "Sample latest_billtext files (up to 200):"
          find latest_billtext -type f -name data.json | sort | sed -n '1,200p' || true

      - name: Build manifests
        run: |
          . env/bin/activate
          $PYTHON -u scripts/build_manifests.py

      - name: Manifest sanity checks
        run: |
          if [ ! -f billtext-manifest.json ]; then
            echo "::error:: billtext-manifest.json not found; aborting"
            exit 1
          fi
          BILLCOUNT=$(jq '.files | length' billtext-manifest.json 2>/dev/null || echo 0)
          echo "billtext-manifest.json contains ${BILLCOUNT} entries"
          if [ "${BILLCOUNT}" -lt 1 ]; then
            echo "::error:: billtext-manifest.json is empty; aborting upload (safety)"
            exit 1
          fi

      - name: Upload Bill Text to GCS
        run: |
          PREFIX="${GCS_PREFIX%/}"
          TARGET_PREFIX="${PREFIX:+${PREFIX}/}data"
          echo "Uploading latest_billtext -> gs://${GCS_BUCKET}/${TARGET_PREFIX}/"
          gsutil -m rsync -r "latest_billtext" "gs://${GCS_BUCKET}/${TARGET_PREFIX}/"

      - name: Upload manifest to GCS
        run: |
          PREFIX="${GCS_PREFIX%/}"
          GS_PREFIX="${PREFIX:+${PREFIX}/}manifests"
          echo "Uploading manifest file to gs://${GCS_BUCKET}/${GS_PREFIX}/"
          gsutil -m cp -n billtext-manifest.json "gs://${GCS_BUCKET}/${GS_PREFIX}/" || true

      - name: Summary
        run: |
          COUNT_TEXT=$(find latest_billtext -type f -name data.json 2>/dev/null | wc -l || echo 0)
          echo "Completed billtext aggregation."
          echo "latest_billtext JSON count: ${COUNT_TEXT}"
          echo "Bucket: ${GCS_BUCKET}"
          echo "Prefix: ${GCS_PREFIX}"
